### ISSUE TITLE
Discourage use of grid role for pure layout purposes

### ISSUE THREAD

**Issue by stes-acc** [w3c/aria#1324] opened 2020-09-18 12:07 UTC
The [ARIA grid role](https://www.w3.org/TR/wai-aria-1.2/#grid) was invented to bridge a gap in HTML: editable, sortable keyboard-navigable tables with row/cell selection and databound labelled cell content organized in rows/colums/cells in fixed x/y positions.

The ARIA APG encourages [usage of grid role for layouting purposes](https://w3c.github.io/aria-practices/#grid).

There are a number of articles out there dealing with the fact that use of grid role for layout purposes should be **discouraged** ([1](https://adrianroselli.com/2020/07/aria-grid-as-an-anti-pattern.html), [2](https://adrianroselli.com/2020/07/aria-grid-as-an-anti-pattern.html)).

Arguments here include responsiveness issues (no constant x/y positioning for various use cases), frolic inconsistent inner keyboard focus movement from cell to content, unclear infinite scrolling scenarios and fundamental contradicting role interaction/edit issues (like layout content never being editable). Read for yourself.

The key issue here is that there may be a small number of use cases where this usage as layout grid works (a tic-tac-toe board maybe with always fixed cell positions and actions on cell level) but its general appliance for all kind of grid-like scenarios is inappropriate.

My personal opinion ist that without an additional attribute indicating usage of grid role for this or even better a complete new role (such as "layoutgrid"), no further attempts should be done to encourage usage of the ARIA grid role for pure layout purposes. 

The ARIA specification should be modified to reflect this to avoid confusion.

**Comment by JAWS-test** [comment] 2020-09-18 13:12
I can only support that. I would appreciate it if grid is only used for tables which are operated with the arrow keys and whose content can be edited inline. 

I find the following sentence in the [specification ](https://www.w3.org/TR/wai-aria-1.2/#grid) particularly problematic: 

> An unspecified value for aria-readonly does not imply that a grid or a gridcell contains editable content. For example, if a grid presents a collection of elements that are not editable, such as a collection of link elements representing dates in a datepicker, it is not necessary for the author to specify a value for aria-readonly.

As a result, AT users can no longer perceive which cells can and cannot be edited. I am for removing the sentence and inserting instead, that every non-editable cell in the grid must be marked with aria-readonly=true (explicitly or implicitly via a parent element)

**Comment by mcking65** [comment] 2020-09-21 05:48
@stes-acc  wrote:

> The ARIA APG encourages [usage of grid role for layouting purposes](https://w3c.github.io/aria-practices/#grid).

One thing we have learned is that layout is not an ideal word here; something more akin to grouping is the real purpose.

@stes-acc  wrote:

> Arguments here include responsiveness issues (no constant x/y positioning for various use cases), frolic inconsistent inner keyboard focus movement from cell to content, unclear infinite scrolling scenarios and fundamental contradicting role interaction/edit issues (like layout content never being editable).

I've read both Adrian's and Sarah's articles. While some legitimate  points are made, I don't find them compelling reasons for constraining grid and then adding still more roles to solve problems that grid is already well-positioned to solve. I think the valid complaints offer arguments for improving the design of the APG examples, clarifying some of the language in the APG examples, improving implementation in frameworks, and working on improving screen reader support.

@stes-acc  wrote:

> The key issue here is that there may be a small number of use cases where this usage as layout grid works (a tic-tac-toe board maybe with always fixed cell positions and actions on cell level) but its general appliance for all kind of grid-like scenarios is inappropriate.

I understand why you would summarize the issue that way. At the same time, if you break the issues down, you might find that solving some of the underlieing problems would lead you to an extremely effective grid role that is far more flexible and much less constrained than you suggest.

There are many circumstances where we need a highly flexible composite container. Over the last few years, we have made sigificant progress solving real world problems that limit the effectiveness of grid as such a container. True, there are more to solve. We can't solve them if the spec unnecessarily constrains grid.

I suggest we close this issue and focus on solving the underlieing issues that constrain grid utility.

**Comment by mcking65** [comment] 2020-09-21 05:55
@JAWS-test  wrote:

> I find the following sentence in the [specification ](https://www.w3.org/TR/wai-aria-1.2/#grid) particularly problematic:
> 
> > An unspecified value for aria-readonly does not imply that a grid or a gridcell contains editable content. For example, if a grid presents a collection of elements that are not editable, such as a collection of link elements representing dates in a datepicker, it is not necessary for the author to specify a value for aria-readonly.
> 
> As a result, AT users can no longer perceive which cells can and cannot be edited. I am for removing the sentence and inserting instead, that every non-editable cell in the grid must be marked with aria-readonly=true (explicitly or implicitly via a parent element)

This assumes that gridcells are inputs and thus can be read-only. But, they are not. A gridcell is a container.

This is an example of how an attribute that could identify a gridcell as having text input capability, like a textbox, would be useful. If we had that, then it would be possible to programatically determine on which cells read-only would be an appropriate property.

**Comment by JAWS-test** [comment] 2020-09-21 10:30
> Your suggestion assumes that gridcells are inputs and thus can be read-only. But, they are not. A gridcell is a container.

@mcking65: ARIA 1.2 says:

> A gridcell may be focusable, **editable**, and selectable

How can I recognize with AT that a gridcell is editable? Of course, a gridcell is only a container, but I would like to know if the container contains only text or other controls, which I can activate with F2.

**Comment by aardrian** [comment] 2020-09-21 13:07
Related: [_Remove layout grid examples_](https://github.com/w3c/aria-practices/issues/1233), issue 1233 at the ARIA Practices.

**Comment by jorycunningham** [comment] 2021-05-06 20:52
I value the ability to use `role="grid" ` to create  a navigation efficiency when there is a list of things that have a lot of interactive sub-things that you may want to skip and enumerated tree-like relationships are inappropriate.

For example:

- A display of several Video Cards with thumbnails, links to the video, links to the author, share buttons
- Lists of items in file directory where each items have multiple controls available to effect them

The goal being to allow the user a mechanism to skim a list of things (up and down arrow) and only dive into its constituent parts if that particular instance seems like the one you want (left and right arrows)

I think that the concern raised about responsive designs changing the relative x/y positioning should be addressed by thinking of the up and down arrow interaction as "previous grouping" and "next grouping", respectively, and left and right arrow as "next item within this group" and "previous item in this group" without getting hung up on directionality. 

I agree that "layout" is a potentially misleading description of non-data grids and would support considering terms such as the use of "composite container" from @mcking65 above

I think the valid concerns from @JAWS-test about the knowability of the internal content of a gridcell (whether or not its content is interactive) could potentially be helped by having firmer language around cell content and focus guidelines and reconsidering the notion that a gridcell itself can be editable and I welcome deep dive on this!

**Comment by devongovett** [comment] 2022-01-22 03:11
What was the outcome of the above discussion? We're currently working on implementing such a card pattern and are struggling to find the right approach. The more I think about it, the less grid makes sense, but I'm not sure what else to use.

**Comment by JAWS-test** [comment] 2022-01-22 14:20
@devongovett https://inclusive-components.design/cards/ may be helpful

**Comment by devongovett** [comment] 2022-01-22 14:44
Yeah I am aware of that. And for individual or small numbers of cards, it's fine. We have potentially 100s or 1000s of cards in a grid-like layout. It's similar to Finder or Google Drive.  You can select cards and perform bulk actions on them, or navigate to a detail view. So aria grid seemed like a useful grouping mechanism to enable arrow key navigation and selection semantics. But given that the columns are not fixed and reflow with the size of the window, I'm not sure it makes sense. I'm wondering if a simple listbox would make more sense, but currently debating about how to get rid of the interactive children within each card that cause all sorts of issues anyway.

**Comment by JAWS-test** [comment] 2022-01-22 22:14
Then a grid seems to me to be the better choice, because a gridcell may contain interactive elements, but an option within a listbox may not.

**Comment by JAWS-test** [comment] 2022-01-22 22:18
The fact that a grid does not have a fixed number of columns (because of reflow) should not be a problem as long as the arrow navigation in the rows and columns works as usual.

In my opinion, a grid can also contain only one column in the source code and in terms of operation (i.e. it can be operated like a listbox with the up and down arrow keys), but visually it can have several columns, which then simply receive the focus one after the other.

**Comment by jnurthen** [comment] 2023-09-09 00:48
#2000 is a duplicate of this

**Comment by jnurthen** [comment] 2023-09-09 00:48
as #2000 is on the F2f agenda - closing this

**Closed by jnurthen** 2023-09-09 00:48 UTC
