### ISSUE TITLE
New role for ruby?

### ISSUE THREAD

**Issue by lreis** [w3c/aria#74] opened 2015-07-30 13:41 UTC
Ruby characters [0] are a requirement of Japanese Text Layout and are similar in function to the superscript text described in the dpub-noteref role.

Would this be applicable as a new role?

[0] http://www.w3.org/TR/jlreq/#usage_of_ruby

**Comment by AmeliaBR** [comment] 2015-11-09 20:13
Since ruby has been integrated into HTML, it makes sense to have a way to reflect it in ARIA.  However, I think the relevant role could be more general, and apply to any pronunciation note or gloss.  E.g., wikipedia articles usually provide the International Phonetic Alphabet pronunciation after the key term is first used in the introductory paragraph.  In that sense, this role could be coordinated with the proposed "term" role.  

Ideally, there would be a way to mark up a pronunciation gloss element in such a way that assistive technologies could identify exactly which text it applies to, and exactly which phonetic script is being used to indicate pronunciation.  An advanced screen reader could then adjust its reading of the entire text (i.e., all instances of that term) accordingly, but would not necessarily read out the pronunciation gloss separately from the term.

**Comment by jnurthen** [comment] 2018-05-21 22:42
See https://github.com/w3c/aria/wiki/Plans-regarding-role-parity

We don't have consensus on rp , rt and ruby
More details as to what these could map to would be helpful.

**Comment by jnurthen** [comment] 2019-09-26 22:30
As detailed at https://github.com/w3c/aria/wiki/Plans-regarding-role-parity#no-consensus-yet-will-do-for-1-3 moving to 1.3

**Comment by joanmarie** [comment] 2019-11-19 18:44
Closing as a duplicate of #488.

**Closed by joanmarie** 2019-11-19 18:44 UTC
Labels: question
