### ISSUE TITLE
Consider attribute for "pass-through" behavior

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria#1319] opened 2020-09-03 23:37 UTC
During today's ARIA working group call, we decided we don't necessarily want or need a "key" role.  However, we do want to create a more universal solution for situations where pass-through functionality will be necessary. For instance, we referenced the potential to make a digital audio workstation accessible with piano keys, drum kit controls, etc. as well as touching on the original issue concerning custom onscreen keyboards.

The general idea at this point is an "aria-passthrough"-like attribute (working-name, not necessarily decided) which would indicate the desire to bypass standard behavior and allow single tap activation, or to use gestures/features that would otherwise be "blocked" by VoiceOver / TalkBack, for example. The thinking, not at all finalized or work-shopped yet, is that this Boolean attribute would allow for the passing through of pointer events and directly map to the behavior that already exists for native apps in iOS and Android; thereby, allowing the developer to interpret these however they like.\

thank you / coauthored by @sinabahram  -  This issue closes #730.

**Comment by cookiecrook** [comment] 2020-12-09 17:28
Probably a duplicate of #1215

**Comment by pkra** [comment] 2022-01-10 16:49
Closing this in favor of #1215.

**Closed by pkra** 2022-01-10 16:49 UTC
Labels: duplicate
