### ISSUE TITLE
HTML pre element

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#475] opened 2016-11-10 18:48 UTC
Need role for HTML pre
https://www.w3.org/TR/html51/grouping-content.html#the-pre-element

**Comment by cookiecrook** [comment] 2017-02-14 20:21
Likely dupe of "generic" #525

**Comment by mcking65** [comment] 2017-02-15 07:51
@cookiecrook wrote:

> Likely dupe of "generic" 

We discussed that possibility and concluded that `pre` has distinct semantic value.

**Comment by cookiecrook** [comment] 2017-02-15 14:35
I disagree. `<pre>` is a stylistic element that has no more semantic value than `<div style="white-space: pre">` If the UAs wish to expose the style pre-formatted sections to the APIs, they already have the ability that, without requiring a new ARIA role.

**Comment by cookiecrook** [comment] 2017-02-15 14:37
@stevefaulkner do you have an HTML-AAM editor's opinion on this one?

**Comment by mcking65** [comment] 2017-02-15 19:10
Normally, white space is irrelevant to screen readers. However, `pre` says and shows on screen, that the white space is semantically significant. This is an element where you get to see something important that I do not get to hear.

It would be helpful, for example, if screen readers had the ability to let you know that the white space is important or automatically turn on indentation announcement when reading inside of a pre. I hate reading code on the web because this kind of ability is not there. And, it is not just code where white space formatting can be important.

This does not necessarily have to be done with a role. It could be a property on a generic block container. Or, on a generic container with another property that tells whether it is also a block element.

The choice between adding roles and properties is important. We currently have a fair amount of confusion over roles that are mapped to 'a1' without property 'x' but are mapped to 'a2' with property 'x'. So, that is a decision that requires thoughtful discussion.

**Comment by cookiecrook** [comment] 2017-02-16 07:24
While I agree that UAs should expose the "preformatted" characteristic to AT, the <pre> element itself has no specific semantic meaning, and therefore should not require a new role. I think browsers should also want to expose the fact that `<main style="white-space: pre">` is preformatted, but in doing so, they should not change its role.

**Comment by mcking65** [comment] 2017-02-16 21:13
@cookiecrook wrote:

> While I agree that UAs should expose the "preformatted" characteristic to AT, the `<pre>` element itself has no specific semantic meaning, and therefore should not require a new role. 

The semantic meaning of `pre` is this is a part of the page where the white space is meaningful. That is an important semantic for AT to utilize.

Again, it may not require a role; it might be better done with an ARIA property on a generic role. That is TBD.

@cookiecrook continues:

> I think browsers should also want to expose the fact that `<main style="white-space: pre">` is preformatted, but in doing so, they should not change its role.

I am not sure I agree with this. If browsers were to treat the style equal to the element, how would authors be able to get the effect of the style without communicating the semantics? Surely there are times where the style is important but the white space is not meaningful from an accessibility perspective. 

Shouldn't we avoid putting more accessibility semantics into styles like a plague? Sure, there are some aspects of CSS that have forced us to operate in a fuzzy zone, but seems to me that avoiding more fuz would be good.

**Comment by MichielBijl** [comment] 2017-02-16 22:32
Is there a role for the `code`-element? I would think `code` and `pre` serve similar purposes.

**Comment by AmeliaBR** [comment] 2017-02-17 00:14
When browsers expose the text content of an element to the Accessibility APIs, do they do so before or after whitespace collapsing, and before or after applying soft wraps for text layout?  

If the screen reader _always_ gets passed the raw DOM text content, with arbitrary whitespace from the markup, or if they get passed the text _after_ soft line breaks have been inserted for rendering, then I definitely see a benefit of indicating whether whitespace is meaningful (that is: defined by the author and also rendered by the browser).  

I would vote for exposing it as a property not a role, especially since there are multiple options (e.g., are the line breaks a mix of hard-coded breaks and soft wraps? is all whitespace preserved or only linebreaks?) controlled by the CSS `white-space` property.

`<code>` has additional semantic meaning, `<pre>` does not. You're supposed to use both for a pre-formatted code block, and I think that's a fairly standard markup pattern.  The fact that screen-readers don't have very good features for reading code is another matter. (Parsing indentation level definitely sounds like a helpful added feature!)

**Comment by mcking65** [comment] 2017-02-17 20:03
@MichielBijl commented:

> Is there a role for the  code -element? I would think  code  and  pre  serve similar purposes.

Not yet; that is also part of the ARIA 1.2 HTML parity objective.

@AmeliaBR commented:

> I would vote for exposing it as a property not a role, especially since there are multiple options.

I am leaning in that direction as well, e.g., aria-whitespace="respect|Ignore|default|other-options?" This would tell the browser what to put in the text nodes in the a11y tree.

I would vote for `<pre>` to have an implicit semantic that maps it to a role that represents a generic block container with `aria-whitespace="respect"`. 

By contrast, I would suggest that `style="white-space: pre"` not get automatically mapped. 

Regardless of how we solve this, I believe that the `<pre>` element is semantically meaningful.

@AmeliaBR commented:

> The fact that screen-readers don't have very good features for reading code is another matter.

Oh, some screen readers have excellent features for reading code. But, they are often useless on web pages.

**Comment by cookiecrook** [comment] 2017-02-18 08:24
@AmeliaBR wrote:
> I would vote for exposing it as a property not a role,

Whether text is preformatted is already exposed as a property in computedStyle, so we don't need anything more in web standards to account for this. The platform accessibility API mappings could expose a new system API property where appropriate. Assistive technologies could access this characteristic the same way they access other text formatting options like bold and underlined text.

@mcking65 wrote:
> `aria-whitespace="respect|ignore|default|other-options?"` 

I hope we can avoid another `aria-*` attribute. What are the cases where you see a new attr being necessary?

> By contrast, I would suggest that style="white-space: pre" not get automatically mapped.

Why not? I read this as providing the exact same semantic value (or lack of) as `<pre>`

**Comment by mcking65** [comment] 2017-02-18 15:21
@cookiecrook commented:

> Whether text is preformatted is already exposed as a property in computedStyle, so we don't need anything more in web standards to account for this. The platform accessibility API mappings could expose a new system API property where appropriate. Assistive technologies could access this characteristic the same way they access other text formatting options like bold and underlined text.

This does not work because it does not enable authors to distinguish between presentational styling and semantic styling.

@cookiecrook commented:

> I hope we can avoid another  aria-*  attribute. What are the cases where you see a new attr being necessary?

All cases where authors are using formatting in a semantically significant manner, e.g., code, debugger output, poetry, etc.

> mcking65 previously wrote:
>> By contrast, I would suggest that `style="white-space: pre"` not get automatically mapped.
>
> Why not? I read this as providing the exact same semantic value (or lack of) as `<pre>` 

Authors need to recognize when whitespace is semantically significant and declare it so. My suggestion is that `<pre>` have the implicit semantic but that styling done with CSS not have that implicit semantic. As I previously explained, this is aligned with making HTML semantically meaningful and CSS presentational. I would use the same logic for all similar elements, such as `<strong>` and `<em>`.

This is very similar to the decision as to whether to style text with a heading tag or CSS. In some cases it is a heading and in other cases it is not a heading. If screen readers start having to guess from computed styles, then authors would have to fight against that with role `none` in cases where they guess a screen reader might guess that the style is meaningful but it actually is not.

**Comment by cookiecrook** [comment] 2017-02-19 11:10
In response to my question:
>> What are the cases where you see a new attr being necessary?

@mcking65 replied: 
> All cases where authors are using formatting in a semantically significant manner, e.g., code, debugger output, poetry, etc.

None of these examples require the use of `<pre>`. `<code>` will likely have its own role (#527) and debug output would be covered by `<samp>` (also in #527)... As for poetry, DPUB may wish to consider roles, but it seems out of scope for ARIA in the foreseeable future. 

> This is very similar to the decision as to whether to style text with a heading tag or CSS. 

I don't think the heading example is valid here. There is a clear cut semantic and role for heading. There is not for `<pre>`. It has been used for some of the purposes you mentioned above, but that's only as a convenient styling element. The element itself does not carry any specific meaning.

I think this is more analogous to using `<i>` versus `font-style: italic;` because they are functionally equivalent. Yes, some sites incorrectly use `<i>` as an ad-hoc visual indication of semantic meaning, but that doesn't mean ARIA should give it a role.

**Comment by jnurthen** [comment] 2019-10-02 17:35
No agreement on this - moving to 1.3

**Comment by joanmarie** [comment] 2019-11-19 18:51
We agreed on generic. We may create an additional attribute. See issue #960.

**Closed by joanmarie** 2019-11-19 18:51 UTC
