### ISSUE TITLE
Consider a "token" role for next version

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#689] opened 2018-01-17 21:09 UTC
An example when you have a dropdown autocomplete as you select items little icons appear visually inside the input that correspond to the choice, but are actually inside spans above or below the input that were positioned ... you can see inaccessible examples here.
https://joshuajohnson.co.uk/Choices/

**Comment by slafleche** [comment] 2018-01-17 21:39
I would also see variants to this display where the "tokens" are just added to a list above the input. Much like GitHub handles labels.

You're basically choosing a subset of items from a group with a search. This styles of input saves you from having a very long list of checkboxes.

**Comment by DavidMacDonald** [comment] 2019-06-24 15:57
A token would be a little icon that is overlaid on an input select.
![image](https://user-images.githubusercontent.com/2365411/60033500-af211900-9676-11e9-8e59-402100d2f795.png)

![image](https://user-images.githubusercontent.com/2365411/60033608-e55e9880-9676-11e9-92b9-d98ed53e9fd4.png)

<input aria-token="p1 p2 p3">
<span class="token"  role="token" id="p1>Preset-1</span>

@jnurthen

**Comment by stes-acc** [comment] 2019-06-24 16:13
I highly second this. Plus, tokens can be individually deleted as depicted beautifully above.
In addition, they form up a typed list (list of tokens) like options in a listbox.
They can also individually being focused with keyboard.
A very common example are the name tokens in the "To:" field of an outlook mail message.

**Comment by jnurthen** [comment] 2019-06-24 17:03
@cookiecrook I notice MacOS has native controls for this - https://developer.apple.com/design/human-interface-guidelines/macos/fields-and-labels/token-fields/ 
Is there documentation somewhere about the API mappings of a token field?

**Comment by cookiecrook** [comment] 2019-06-25 06:20
AppKit has an [NSTokenField](https://developer.apple.com/documentation/appkit/nstokenfield), which provides the token UI and keyboard behavior of the surrounding text/object siblings. The behavioral difference of native tokens is that they can be buttons that are also selectable text chars (single atomic char representing the full token)... That said, I've never seen web UI that does text selection well for token views.

To answer your question directly, the mapping of the macOS UI is an AXTextAttachment inside an AXTextField, but I would not suggest ARIA map anything like that. Implementations of native tokens usually rely on an "object replacement character" inside a standard text field. I'm not certain that is currently possible in an HTML DOM context, though `contenteditable` images may be done similarly. In any case, I've never seen web tokens implemented this way, and I don't think most web authors would think to do it this way (descendant of a text field), so the current macOS mapping is probably irrelevant for this discussion.

For web teams trying to make token-like UI accessible, we usually recommend the token field be a single auto-complete field, and as entries are added, the "tokens" are inserted as buttons before the field.

I don't have a strong opinion whether or not a `token` role should be added, but IMO the `tokenfield` is the more useful of the two. The field defines the interesting behavior. The token is just a button inside that field...

**Comment by cookiecrook** [comment] 2019-06-25 06:34
@stes-acc wrote:
> They can also individually being focused and selected (!) with keyboard.
> A very common example are the name tokens in the "To:" field of an outlook mail message.
> There are numerous examples for this in the Web, for instance [here](https://openui5.hana.ondemand.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInputMaxTokens).

This is one of the examples I mentioned where keyboard behavior is implemented incompletely. You can't select them as part of the same field (e.g. with shift+arrows) or move the insertion between, so these don't act like native tokens. They just act like buttons inserted before the text field.

That said, the widget author did implement some capturing of the arrows and delete keys, so hearing "token" in the role description might make it a little easier to understand why the arrow key interception and focus changes are happening.

**Comment by cookiecrook** [comment] 2019-06-25 06:44
<img width="1056" alt="Web Inspector showing David's example is implemented as a text field following buttons, rather than tokens inside a selectable text range" src="https://user-images.githubusercontent.com/75867/60074932-f7712300-96d8-11e9-8999-8c77030f2520.png">

Inspecting both examples linked and the GitHub example @slafleche mentioned, these are all implemented as buttons before text fields. Not really the same functionality of a native token field, but probably still different enough from standard buttons to warrant a new role or two.

**Comment by jnurthen** [comment] 2019-06-25 16:57
(if we go down this path) Alternate names I have seen used for these are "tag" and "pill" instead of "token"

**Comment by cookiecrook** [comment] 2019-06-25 18:01
Not `tag` please. That's a much narrower semantic use of a similar visual UI.

**Comment by carmacleod** [comment] 2019-06-25 22:52
> Alternate names I have seen used for these are "tag" and "pill" instead of "token"

Also, "chiclet" (believe it or not).

**Comment by AmeliaBR** [comment] 2019-06-25 23:35
Before getting too deep into a naming discussion, it's worth considering the scope of the role:

- Does it apply to the entire widget, meaning the input field, any drop-downs, and the list of currently selected values?

- Or should the role only apply to the individual value, and it's cancel button?  The list box or combo-box that adds tokens would then be a separate widget.

Either way, we need to consider how to represent the relationship between the list of currently-selected tokens and the input that adds new values.

Its also worth considering other presentations of widgets with the same semantics.  E.g., consider the GitHub widget for adding labels or assignees to an issue. It doesn't use a "pill" view but instead lists the currently selected values at the top of the drop-down list of other available options, after the type-ahead input field.  

Regardless of the final scope, I would strongly argue for names based on semantics and not the currently fashionable visual presentation (text on a solid background with rounded corners, AKA a pill shape).

**Comment by carmacleod** [comment] 2019-06-26 19:31
The semantics of the "widget as a whole" are wild.  :)

It's _almost_ like a "multiselectable" combobox that "controls" tokens as well as its dropdown list.
(I'm not suggesting re-using combobox! It is already overloaded. I'm just using it to compare semantics).

One complication that I have seen is that in addition to having an X to remove tokens from the selected list, they can be "activated" like a button. For example, in an email "To:" or "CC:" list, clicking on a token opens a contact info card. Or, it might turn a token back into text so that they can be edited in the input field.

**Comment by mcking65** [comment] 2020-09-04 01:44
I'd like for us to strongly consider every possible way of resolving this without another role. Thinking as a user, I don't want to learn the meaning of one more role. As an author, do I really need another role? If my "token" has characteristics of a button or link, why not just use a button or link role? I have a hunch we can solve this with patterns that employ existing roles.

**Comment by stes-acc** [comment] 2020-09-08 14:58
Is aria-roledescription="Token" ok? We need APG examples.

**Comment by scottaohara** [comment] 2020-09-08 15:20
that would just overwrite the announcement of the underlying role of the element, disguising its purpose.  would agree with matt here, what value does a "token" have to someone where an established role would better communicate how it would function.

**Comment by stes-acc** [comment] 2020-09-08 15:34
I strongly disagree. Overwriting the announcement is always happening. If this is not wanted, we would need a strict limitation of use cases of aria-roledescription which is NOT specified so far in current ARIA spec. 

Going forward this path we would also forbid using role="button" on a HTML anchor, something that is also in a gray zone and topic of [ARIA in HTML](https://www.w3.org/TR/html-aria/).

But I am with you if you saying role=token is more straight here.

**Comment by scottaohara** [comment] 2020-09-08 16:34
talking about two different things here.

changing a native anchor to be exposed as a button via role=button, and using aria-roledescription to announce a button as a "token" which has no agreed upon/universally known meaning, are quite different.

**Comment by stes-acc** [comment] 2020-09-09 08:07
Partly correct. The speech output override is the same. The API mapping is not.

In addition, it would be wrong to give a token a base role of button since all its semantics are different. A base class of listitem with aria-roledescription="Token" in a Token list is a better mapping which also allows for token position info and acceptance of special properties like being "deletable".

It is about time that HTML input and select/combo elements reflect contemporary extensions like this one for tokens being intrinsic part of an input and not a faked add-on.

The discussion should be more biased towards this, browser vendors involved.

**Comment by scottaohara** [comment] 2020-09-09 13:42
>Partly correct. The speech output override is the same. The API mapping is not.

I wasn't indicating otherwise...  "token" having no api mapping though, and being generally meaningless as it's design/ui jargon... comparing api mappings here isn't relevant.

>In addition, it would be wrong to give a token a base role of button since all its semantics are different...

except for instances where it would be appropriate.  there is no 100% agreed upon pattern/ux for a "token".  so that statement is more opinion than fact at this point.

>It is about time that HTML input and select/combo elements reflect contemporary extensions

that's why the "open ui" tag was added to this thread.  next steps should be engaging with that group, and as Matt says, see if there aren't ways we can move forward with this concept without introducing roles that have no universally accepted understanding or meaning.

**Comment by aleventhal** [comment] 2020-09-21 16:00
We have a Chrome bug filed for this as well -- at least the attempted code does not work in Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=991203

**Comment by brennanyoung** [comment] 2022-06-13 08:13
Material calls this a "chip". The one with the close box is called an "inputchip". I don't really like these names. Makes me think of casinos or snacks.

https://m3.material.io/components/chips/guidelines

**Comment by brennanyoung** [comment] 2022-11-01 12:55
I notice that ebay is using `<a>` for these. 
Can anyone suggest why they made this choice? Is it ok?

The HTML5 spec for `<a>` (like ARIA's "link" role) forbids interactive descendents, which means that a separate 'close box' inside the chip is going to cause trouble. These are common. What do we do here?
The HTML5 spec for `<a>` without href forbids naming. 

Seems to me that '<a>' is no more suitable than checkbox or button.

**Comment by brennanyoung** [comment] 2022-11-01 14:15
Important note: Some implementations of "token" support re-ordering by drag-and-drop. I've never seen this with button/checkbox/radiobutton/link.

**Comment by brennanyoung** [comment] 2022-11-03 13:06
> that's why the "open ui" tag was added to this thread. next steps should be engaging with that group, and as Matt says, see if there aren't ways we can move forward with this concept without introducing roles that have no universally accepted understanding or meaning.

[open ui has marked the issue as "stale"](https://github.com/openui/open-ui/issues/226).
How can we move this along?

**Comment by pkra** [comment] 2022-11-03 13:31
>  How can we move this along?

The issue is on the aria 1.4 milestone and aria 1.3 does not have a first public working draft yet. 

@scottaohara is this topic something for #1832 perhaps?

**Comment by brennanyoung** [comment] 2022-11-03 14:08
All the suggested names have flaws, but I strongly agree with @AmeliaBR :
> I would strongly argue for names based on semantics and not the currently fashionable visual presentation.

Also there are several different kinds of "token" or "chip". (I'm gonna use "chip" here). They don't all behave the same way, and their behavior may depend on a the higher-level widget that contains them (often some kind of option list, or input field).  Without getting distracted by the similarities or differences of their appearance, it would be valuable to determine whether these different kinds of chip are actually distinct types of element or whether they are a 'family' of component types with some taxonomical relationship.

### Common Use Cases

- In editable email/messaging recipient lists. (Reorder, remove)
- As lightweight wrappers for hashtags and similar under a post. Often, these function as hyperlink searches.
- As removable filters for search results (e.g. ebay) 
- As booleans included in a form submission. (Pseudo checkboxes).

any more?

### Questions/Comments

- Are chips "phrasing content"? I think so. AFAICT Chips are invariably "inline". Any exceptions?
- Should there be any rules, constraints or guidelines about the semantic context where chips are permitted? For example, should a filter chip be required to be a child of (or have some semantic association with) a container with `role="search"`?
- Some chips have something that looks like a close box, but semantically it is "remove" rather than "close".
- Should chips be tab stops? Or should focus be managed by the the containing widget?
- How does the close box (more correctly, the "remove" button) fit into the tab sequence, ideally?
- If a token is in focus and you press "Delete" on the keyboard, I think it should behave as if the "remove" button has been clicked. (If there is a one). Any dissenting opinions on this?
- Quite a few of the implementations "in the wild" support **reordering** of chips/tokens (typically by drag-and-drop). Suggest viable keyboard interface for this? What about touchscreens? How to distinguish reordering from deleting?
- If not via `role` (or `aria-roledescription`) What cues may be offered to indicate that chips may be deleted, reordered, deselected? 
- Consider aria live regions and `aria-relevant="removals"` - to provide AT cues that the deletion actually occurred.
- Some chips behave more like toggle buttons or checkboxes (can't be removed, but can be 'unchecked'). These may be implemented today as `<button>` with a value for `aria-pressed`, or even as role="switch". Which is better? APG?
- I've seen chip-like elements which are basically radio button groups. **Existing ARIA can handle these cases**. APG?

### If a chip/token is implemented as `<a>` (as ebay does):

- What's the "href"? Is it null? In which case [naming is prohibited](https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/)!
- For both `<a>` and role="link", focusable child elements (e.g. the closebox) are forbidden.
- `<a>` might yet be appropriate in some cases (e.g. tag cloud under a post, where each tag is a search url)

Possible implementations (APG?) with today's specs:

- Wrapper `<ol>` with Chips as `<li>`, with `<button>` "remove" inside - `<ol>` to support the notion of **re-ordering**.
- Wrapper `role="group"` seems viable in some cases. For more elaborate implementations I'm looking at `role="application"`.
- chips as `<a>`. visible "remove" button is purely presentational. Chip itself responds to "Delete" key when in focus

**Comment by stes-acc** [comment] 2023-02-15 15:01
We need an APG proposal for this. Still aria-roledescription="token button" would be my favorite.

**Comment by brennanyoung** [comment] 2023-05-31 09:32
Given that so much of the complexity of tokens/chips comes from their "secondary actions" (delete/reorder) I'm wondering if this might be approached as part of https://github.com/w3c/aria/issues/1440

**Comment by slafleche** [comment] 2023-05-31 17:35
> Given that so much of the complexity of tokens/chips comes from their "secondary actions" (delete/reorder) I'm wondering if this might be approached as part of #1440

I agree 100% that this fits into a broader need for a way to describe secondary actions. Custom implementations need to be described as such. However, I believe they are common enough to merit their own label. It will be easier and quicker for the user to understand what the input is.

**Comment by slafleche** [comment] 2023-06-02 17:39
> @brennanyoung Delete/remove obviously useful, but does anyone know of a real-world example where the _reordering_ of tokens is useful or critical? I don’t recall seeing that as a UI at term.

Although tokens may often be "flat", there are cases where there's a hierarchy. 

Say you're on a forum, and users can have multiple roles. The user may want to chose the order their roles appear on their profiles, putting the most important roles to them first.

**Comment by jnurthen** [comment] 2024-06-06 17:48
closing - this should be in HTML before ARIA. If HTML creates this then we should revisit.

**Closed by jnurthen** 2024-06-06 17:48 UTC
Labels: openui
