### ISSUE TITLE
Move the text "User agents MUST provide a way for assistive technologies to be notified when states change, either through DOM attribute change events or platform accessibility API events." from 6.5.1 to the end of section 6.5

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#732] opened 2018-05-03 20:51 UTC
Migrated from [Bug 26038](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26038)

**Comment by jnurthen** [comment] 2019-09-27 18:05
Agree that the widgets section (http://w3c.github.io/aria/#attrs_widgets) seems like a strange location for this text

I see this potentially as a sibling to http://w3c.github.io/aria/#ua_domchanges

**Comment by jnurthen** [comment] 2022-09-20 00:48
From digging through the old minutes the issue is that this text applies to more than just widget attributes (globals for instance also should do this) so it needs moving to apply to all. Not sure the end is the right place

**Closed** 2023-01-19 18:40 UTC
Labels: editorial
