### ISSUE TITLE
CORE-AAM 1.1: Create MacOSX Mappings for aria-rowcount

### ISSUE THREAD

**Issue by richschwer** [w3c/aria#462] opened 2016-11-02 18:48 UTC
Moved from tracker action: https://www.w3.org/WAI/ARIA/track/actions/2119

**Comment by richschwer** [comment] 2016-11-02 18:51
Note: one issue we are discussing with NVDA and Freedom Scientific is the issue of dealing with aria-colindex and aria-rowindex, aria-rowspan, aria-colspan in the mappings when rows or columns are discontinuous.

**Comment by cookiecrook** [comment] 2016-12-14 07:51
Dupe of #459

**Closed by cookiecrook** 2016-12-14 07:51 UTC
