### ISSUE TITLE
CORE-AAM: term role mappings restrict use to list item

### ISSUE THREAD

**Issue by jasonkiss** [w3c/aria#455] opened 2016-11-02 03:48 UTC
Just want to confirm that the [CORE-AAM mappings for role="term"](http://w3c.github.io/aria/core-aam/core-aam.html#role-map-term) are intended to restrict it to list items as patterned by the `dt` element in HTML. 

The ARIA 1.1 descriptions of the [term role](http://w3c.github.io/aria/aria/aria.html#term) and the [definition role](http://w3c.github.io/aria/aria/aria.html#definition) are more general, and don't imply, at least to me, their restriction to a list structure.

I'm looking at this because I was thinking/hoping that the mappings for the term role might make it a good match for the [`dfn` element](https://www.w3.org/TR/html51/textlevel-semantics.html#the-dfn-element), which is described as "the defining instance of a term". That seems to overlap with the description of the term role as "a word or phrase with a corresponding definition".

If the current CORE-AAM mappings for the term role are as intended, then the description of the term role (and the definition role?) needs to be narrowed in the ARIA spec. Otherwise, any use of the term role around a word or phrase with a definition will pick up list item semantics, which won't be appropriate in all sorts of cases.

**Comment by joanmarie** [comment] 2017-08-02 10:17
Thanks @jasonkiss. As you can see, I've opened issues #617 and #618 for UIA and MSAA/IA2 respectively since we need input from each platform. And a given platform may decide to punt for now, pending better platform roles being added to their API.

**Comment by joanmarie** [comment] 2017-08-04 18:27
It's no longer a listitem for IA2. At this point, UIA is the only platform which has a listitem mapping.

**Comment by joanmarie** [comment] 2017-09-13 22:07
Closing this as a duplicate of #617 and #618. As a result of those issues being fixed, https://w3c.github.io/aria/core-aam/core-aam.html#role-map-term no longer has any list-item-related mappings.

**Closed by joanmarie** 2017-09-13 22:07 UTC
Labels: AAM, ARIA 1.1, blocked, Core-AAM
