### ISSUE TITLE
CORE-AAM: need UIA mapping for timer

### ISSUE THREAD

**Issue by cyns** [w3c/aria#418] opened 2016-08-02 19:30 UTC

**Comment by klown** [comment] 2016-08-02 20:13
@cyns, the current mapping is:
https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-timer

**Comment by joanmarie** [comment] 2017-08-02 09:36
Closing as a duplicate of #614.

**Closed by joanmarie** 2017-08-02 09:36 UTC
