### ISSUE TITLE
Role Parity for semantically meaningless stylistic elements in HTML

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#485] opened 2016-11-17 18:56 UTC
Need to have semantic features that cover the types of text emphasis, such as 
* em https://www.w3.org/TR/html51/textlevel-semantics.html#the-em-element, 
* strong https://www.w3.org/TR/html51/textlevel-semantics.html#the-strong-element, 
* i https://www.w3.org/TR/html51/textlevel-semantics.html#the-i-element, 
* b https://www.w3.org/TR/html51/textlevel-semantics.html#the-b-element, 
* u https://www.w3.org/TR/html51/textlevel-semantics.html#the-u-element, 
* sub and sup https://www.w3.org/TR/html51/textlevel-semantics.html#the-sub-and-sup-elements, 
* small https://www.w3.org/TR/html51/textlevel-semantics.html#the-small-element, 
* s https://www.w3.org/TR/html51/textlevel-semantics.html#the-s-element
* ins https://www.w3.org/TR/html51/edits.html#the-ins-element
* del https://www.w3.org/TR/html51/edits.html#the-del-element
* code https://www.w3.org/TR/html51/textlevel-semantics.html#the-code-element
* var https://www.w3.org/TR/html51/textlevel-semantics.html#the-var-element
* samp https://www.w3.org/TR/html51/textlevel-semantics.html#the-samp-element
* kbd https://www.w3.org/TR/html51/textlevel-semantics.html#the-kbd-element
* cite https://www.w3.org/TR/html51/textlevel-semantics.html#the-cite-element
* q https://www.w3.org/TR/html51/textlevel-semantics.html#the-q-element

Some of these attributes are "semantic" and some are "style" but different would say different things about which which. Need to sort that out in ARIA mappings, with focus on semantics. Some spin-off issues may be needed for some of the attributes.

**Comment by michael-n-cooper** [comment] 2016-11-17 18:56
Would be helpful to have a CSS person help out.

**Comment by michael-n-cooper** [comment] 2017-01-05 18:41
[5 January 2017 ARIA Telecon](https://github.com/w3c/aria/issues/507) group might want to separate code out.

**Comment by michael-n-cooper** [comment] 2017-02-02 18:45
[2 February 2017 telecon](http://www.w3.org/2017/02/02-aria-minutes.html) @Joanmarie cares especially about ins and del.

**Comment by cookiecrook** [comment] 2017-02-14 20:00
Is this is about `<em>`, it's likely a dupe of "generic" #525

**Comment by cookiecrook** [comment] 2017-02-14 20:14
The first listed elements are generics: em, strong, I, b, u, sub, sup, small, s, etc....

The others listed at the top should be their own issues. I've filed:
- #526 for ins/del
- #527 for code/var/samp/kbd
- #528 for blockquote/cite/q

**Comment by mcking65** [comment] 2017-02-15 08:05
@cookiecrook wrote:

> The first listed elements are generics: em, strong, I, b, u, sub, sup, small, s, etc....

We had that discussion and concluded that these elements are in an area where semantics intersect with style. These types of "style" have semantic significance, and in many contexts have specific meanings. 

We agreed that communicating the semantics associated with these elements is important. 

How that might be done is TBD. One possibility is a generic role that represents inline elements coupled with an aria-property.

**Comment by scottaohara** [comment] 2019-10-14 23:12
Closing this issue as all mentioned elements have been either received role parity, have open issues for them, have been closed, or have been pushed to 1.3:

* [em](https://rawgit.com/w3c/aria/master/#emphasis) - ED
* [strong](https://rawgit.com/w3c/aria/master/#strong) - ED
* [i](https://github.com/w3c/aria/issues/960) - new issue
* [b](https://github.com/w3c/aria/issues/960) - new issue
* [u](https://github.com/w3c/aria/issues/960) - new issue
* [sub](https://rawgit.com/w3c/aria/master/#subscript)/[sup](https://rawgit.com/w3c/aria/master/#superscript) - ED
* [small](https://github.com/w3c/aria/issues/960) - new issue
* [s](https://github.com/w3c/aria/issues/960) - new issue
* [ins](https://rawgit.com/w3c/aria/master/#insertion) - ED 
* [del](https://rawgit.com/w3c/aria/master/#deletion) - ED
* [code](https://rawgit.com/w3c/aria/master/#code) - ED
* [var](https://github.com/w3c/aria/issues/527) - issue
* [samp](https://github.com/w3c/aria/issues/527) - issue
* [kbd](https://github.com/w3c/aria/issues/527) - issue
* [cite](https://github.com/w3c/aria/issues/873) - closed as generic
* [q](https://github.com/w3c/aria/issues/528) - generic inline

**Closed by scottaohara** 2019-10-14 23:12 UTC
Labels: ARIA 1.2
