### ISSUE TITLE
Required aria-controls must be allowed to point to IDs of elements NOT in the DOM

### ISSUE THREAD

**Issue by stes-acc** [w3c/aria#2049] opened 2023-09-26 11:59 UTC
Currently validators complain when aria-controls is defined with ID's pointing to elements not being present in DOM (combobox popup in collapsed state) but instantiated at a later point in time (for instance following an expand request).

Requiring that authors should put referenced content ALWAYS permanently present in DOM to avoid these kind of errors is no solution since addressing dynamic application scenarios also with performance and efficiency reasons in applications always require dynamically created UI parts. 

For instance, **https://www.w3.org/TR/wai-aria-1.2/#combobox does not say expicitely say WHEN aria-controls has to be present and to be checked for correctness, so validators check this always for expanded and non-expanded state.**

The ARIA spec should clarify this situation by explicitely defining cases for aria-controls checks as part of the role attribute specifications that validators have a solid advice what to check.

This can even be generalized for all properties mandatory present pointing to element IDs (aria-labelledby, describedby etc.) and should therefore best centrally defined/clarified.

## Will this require a change to the [ARIA authoring guide](https://w3c.github.io/aria-practices/)?

https://www.w3.org/WAI/ARIA/apg/patterns/combobox/

•	The combobox element has [aria-controls](https://w3c.github.io/aria/#aria-controls) set to a value that refers to the element that serves as the popup. Note that aria-controls only needs to be set when the popup is visible. However, it is valid to reference an element that is not visible

The text says nothing about th fact that hidden may mean also not being present in DOM. So yes, it WILL require a change in wording to clarify that.

**Comment by pkra** [comment] 2023-09-26 14:21
What's the difference compared to https://github.com/w3c/aria/issues/1956 ?

**Comment by jnurthen** [comment] 2023-09-26 15:25
closing as duplicate of #1956

**Closed by jnurthen** 2023-09-26 15:25 UTC
