### ISSUE TITLE
HTML-AAM: possible abbr attr/el confusion?

### ISSUE THREAD

**Issue by aardrian** [w3c/aria#2343] opened 2024-09-27 00:02 UTC
3.5.4 `<abbr`> entry for MSAA/IA2:
https://w3c.github.io/html-aam/#el-abbr

> Roles: ROLE_SYSTEM_TEXT; IA2_ROLE_TEXT_FRAME
Object attributes: "abbr" attribute on the containing [td](https://w3c.github.io/html-aam/#el-td) if a single child, text content used as a value

3.6.1 `abbr` attribute entry for MSAA/IA2:
https://w3c.github.io/html-aam/#att-abbr

> Object attributes: "abbr" until child [abbr](https://w3c.github.io/html-aam/#el-abbr) element is provided

Questions:
1. Are these descriptions partially / completely swapped?
2. The `abbr` attribute lives on `<th>`, not `<td>`, yeah?
3. The `abbr` attribute should not have a child `<abbr>`, right?
4. Should I blame the loud pool here at TPAC?

Checking with an issue to confirm this is weird before I file a PR.

**Comment by scottaohara** [comment] 2024-09-27 00:09
it is wrong, and has been for awhile - https://github.com/w3c/html-aam/issues/246

if a PR can be filed, that'd be wonderful

**Comment by pkra** [comment] 2024-09-27 07:23
Can we close this as a duplicate of https://github.com/w3c/html-aam/issues/246 ?

**Comment by spectranaut** [comment] 2024-10-10 17:46
closing as dup of: https://github.com/w3c/html-aam/issues/246
Assigning @aardrian there

**Closed by spectranaut** 2024-10-10 17:46 UTC
Labels: editorial
