### ISSUE TITLE
[Role Parity] What do we do about object?

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#938] opened 2019-04-09 18:13 UTC

**Comment by jnurthen** [comment] 2019-09-26 22:34
As detailed at https://github.com/w3c/aria/wiki/Plans-regarding-role-parity#no-consensus-yet-will-do-for-1-3 moving to 1.3

**Comment by joanmarie** [comment] 2019-11-21 18:48
Tentative consensus: New embeddedobject role. Largely a generic herebedragons container to preserve exposure via platform accessibility APIs.

**Comment by scottaohara** [comment] 2019-11-21 18:49
per today's conversation, closing this as a dupe of #929

**Closed** 2019-11-21 18:51 UTC
