### ISSUE TITLE
input format property

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#466] opened 2016-11-03 17:32 UTC
Provide new attribute property that aligns with HTML 5.1 type https://www.w3.org/TR/2016/REC-html51-20161101/sec-forms.html#element-attrdef-input-type

**Comment by michael-n-cooper** [comment] 2016-11-03 17:34
Note the lovely password issue #166 could potentially also be handled as a format type under this issue. https://www.w3.org/2016/11/03-aria-minutes.html

**Comment by cookiecrook** [comment] 2017-02-14 20:24
If ARIA 1.2 is still limited to HTML Role Parity, this issue is not in scope.

**Comment by joanmarie** [comment] 2019-11-12 18:24
Marking as a duplicate of #962. (Yeah, I know this one here came first, but I hadn't seen it when I opened #962, and the newer issue has more discussion.)

**Closed by joanmarie** 2019-11-12 18:24 UTC
